name: Release
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Using the latest Node.js version

      - name: Install dependencies
        run: npm install

      - name: Set up Git user
        uses: fregante/setup-git-user@v1

      - name: Publish to VSCode Marketplace
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
